# Generated by Django 2.0.5 on 2018-06-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
